apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webhookService.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.webhookDeployment.port }}
      targetPort: {{ .Values.webhookDeployment.port }}
  selector:
    app: {{ .Values.webhookDeployment.appLabel }}
