apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nodeselector-mutating-webhook-hpa
  namespace: nodeselector-mwh
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodeselector-mutating-webhook
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
